CREATE TABLE CFE_USERS
(
  ID         BIGINT(20) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  CREATED_AT TIMESTAMP              NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP              NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  MSG_SEQ_NR BIGINT(20)             NOT NULL,
  EMAIL      TEXT                   NOT NULL,
  FIRST_NAME TEXT                   NOT NULL,
  LAST_NAME  TEXT                   NOT NULL
)
